// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldcofddghsruqarlgagh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkY29mZGRnaHNydXFhcmxnYWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjQ4MTUsImV4cCI6MjA3MTMwMDgxNX0.TuoRHeBuDkCH4cAJNx4wX9fO_YIz1kl1RyFNwIe2nXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});